
package client;

import jakarta.xml.ws.*;
import server.ServerImpl;
import server.ServerInterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MontrealServerImplService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8082/server/montreal/?wsdl")
public class MontrealServerImplService
    extends Service
{

    private final static URL MONTREALSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MONTREALSERVERIMPLSERVICE_EXCEPTION;
    private final static QName MONTREALSERVERIMPLSERVICE_QNAME = new QName("http://server/", "MontrealServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/server/montreal/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONTREALSERVERIMPLSERVICE_WSDL_LOCATION = url;
        MONTREALSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public MontrealServerImplService() {
        super(__getWsdlLocation(), MONTREALSERVERIMPLSERVICE_QNAME);
    }

    public MontrealServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONTREALSERVERIMPLSERVICE_QNAME, features);
    }

    public MontrealServerImplService(URL wsdlLocation) {
        super(wsdlLocation, MONTREALSERVERIMPLSERVICE_QNAME);
    }

    public MontrealServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONTREALSERVERIMPLSERVICE_QNAME, features);
    }

    public MontrealServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MontrealServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MontrealServerImpl
     */
    @WebEndpoint(name = "MontrealServerImplPort")
    public MontrealServerImpl getMontrealServerImplPort() {
        return super.getPort(new QName("http://server/", "MontrealServerImplPort"), MontrealServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MontrealServerImpl
     */
    @WebEndpoint(name = "MontrealServerImplPort")
    public MontrealServerImpl getMontrealServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "MontrealServerImplPort"), MontrealServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONTREALSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw MONTREALSERVERIMPLSERVICE_EXCEPTION;
        }
        return MONTREALSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
