
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuebecServerImplService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8082/server/quebec/?wsdl")
public class QuebecServerImplService
    extends Service
{

    private final static URL QUEBECSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUEBECSERVERIMPLSERVICE_EXCEPTION;
    private final static QName QUEBECSERVERIMPLSERVICE_QNAME = new QName("http://server/", "QuebecServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/server/quebec/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUEBECSERVERIMPLSERVICE_WSDL_LOCATION = url;
        QUEBECSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public QuebecServerImplService() {
        super(__getWsdlLocation(), QUEBECSERVERIMPLSERVICE_QNAME);
    }

    public QuebecServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUEBECSERVERIMPLSERVICE_QNAME, features);
    }

    public QuebecServerImplService(URL wsdlLocation) {
        super(wsdlLocation, QUEBECSERVERIMPLSERVICE_QNAME);
    }

    public QuebecServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUEBECSERVERIMPLSERVICE_QNAME, features);
    }

    public QuebecServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuebecServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuebecServerImpl
     */
    @WebEndpoint(name = "QuebecServerImplPort")
    public QuebecServerImpl getQuebecServerImplPort() {
        return super.getPort(new QName("http://server/", "QuebecServerImplPort"), QuebecServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuebecServerImpl
     */
    @WebEndpoint(name = "QuebecServerImplPort")
    public QuebecServerImpl getQuebecServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "QuebecServerImplPort"), QuebecServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUEBECSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw QUEBECSERVERIMPLSERVICE_EXCEPTION;
        }
        return QUEBECSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
